# Generated by Django 3.1.4 on 2021-03-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='img_link',
            field=models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='api.media'),
        ),
    ]
