# Generated by Django 3.1.4 on 2021-03-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210323_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
