# Generated by Django 3.1.4 on 2021-03-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
