# Generated by Django 3.1.4 on 2021-05-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210324_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
